version: '3'

services:

  db:
    restart: always
    image: postgres:9.6-alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis:4.0-alpine
    volumes:
      - ./redis:/data

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.worker
    command: celery -A wort beat
    links:
      - redis

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    image: wort-worker
    depends_on:
      - celery-beat
    links:
      - redis

  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: >
      gunicorn -b 0.0.0.0:5000
        --access-logfile -
        --reload
        "wort.app:create_app()"
    environment:
      PYTHONUNBUFFERED: 'true'

#    entrypoint:
#      - flask
#      - run
#      - --host=0.0.0.0
#    environment:
#      FLASK_DEBUG: 1
#      FLASK_APP: ./app.py
    ports:
      - "5000:5000"
    links:
      - redis
      - db
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
