version: '3'

services:

  db:
    restart: always
    image: postgres:9.6-alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - env.production

  redis:
    restart: always
    image: redis:4.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.worker
    command: celery -A wort.blueprints.compute.tasks beat
    links:
      - redis

  celery-flower:
    build:
      context: .
      dockerfile: Dockerfile.flower
    image: flower
    ports:
      - "5555:5555"
    links:
      - redis
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    image: wort-worker
    links:
      - redis
    env_file:
      - iam/wort_s3.env

  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: >
      gunicorn -b 0.0.0.0:5000
        --access-logfile -
        --reload
        "wort.app:create_app()"
    environment:
      PYTHONUNBUFFERED: 'true'
      FLASK_APP: 'wortapp.py'
    ports:
      - "5000"
    links:
      - redis
      - db
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    env_file:
      - env.production

  proxy:
    restart: always
    build:
      context: nginx
      dockerfile: Dockerfile
    volumes:
      - ./letsencrypt_certs:/etc/nginx/certs
      - ./letsencrypt_www:/var/www/letsencrypt
    ports:
      - "80:80"
      - "443:443"

  letsencrypt:
    image: certbot/certbot
    command: /bin/true
    volumes:
      - ./letsencrypt_certs:/etc/letsencrypt
      - ./letsencrypt_www:/var/www/letsencrypt
